services:
  api-gateway:
    image: comauro7511/api-gateway
    build: 
      context: ./graphql-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - user-service
      - order-service
      - product-service
      - redis
    environment:
      USER_SERVICE_URL: http://user-service:3000
      ORDER_SERVICE_URL: http://order-service:3000
      PRODUCT_SERVICE_URL: http://product-service:3000
      REDIS_HOST: redis
    restart: unless-stopped

  user-service:
    image: comauro7511/users
    build: 
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - postgres-users
      - nats-streaming
    environment:
      DATABASE_URL: postgres://postgres:password@postgres-users:5432/usersdb
      NATS_URL: nats://nats-streaming:4222
      NATS_CLUSTER_ID: syncchain
      NATS_CLIENT_ID: user-service
  
    restart: unless-stopped

  order-service:
    image: comauro7511/orders
    build: 
      context: ./orders
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    depends_on:
      - postgres-orders
      - nats-streaming
    environment:
      DATABASE_URL: postgres://postgres:password@postgres-orders:5432/ordersdb
      NATS_URL: nats://nats-streaming:4222
      NATS_CLUSTER_ID: syncchain
      NATS_CLIENT_ID: order-service
    restart: unless-stopped

  product-service:
    image: comauro7511/products
    build: 
      context: ./products
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    depends_on:
      - postgres-products
      - nats-streaming
    environment:
      DATABASE_URL: postgres://postgres:password@postgres-products:5432/productsdb
      NATS_URL: nats://nats-streaming:4222
      NATS_CLUSTER_ID: syncchain
      NATS_CLIENT_ID: product-service
    restart: unless-stopped

  nats-streaming:
    image: nats-streaming:0.17.0
    command:
      - "-p"
      - "4222"
      - "-m"
      - "8222"
      - "-hbi"
      - "5s"
      - "-hbt"
      - "5s"
      - "-hbf"
      - "2"
      - "-SD"
      - "-cid"
      - "syncchain"
    ports:
      - "4222:4222"
      - "8222:8222"
    restart: unless-stopped

  postgres-users:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres-users-data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-orders:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres-orders-data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-products:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - postgres-products-data:/var/lib/postgresql/data
    restart: unless-stopped
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped
  
volumes:
  postgres-users-data:
  postgres-orders-data:
  postgres-products-data: 